openapi: 3.0.1
info:
  title: Minio Server
  description: "This is the api for Minio."
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: authenticate
    description: "The endpoint for authentication. Here you can register you clients in order to begin with the socket communication"
  - name: assset
    description: "The endpoint for managing necessary assets."
  - name: channel
    description: "The endpoint for publish and subscribe within a namespace"
  - name: collection
    description: "CRUD operations for the collections. A collection is the represantation of a list of entries in the database"
paths:
  /authenticate:
    post:
      tags:
        - authenticate
      summary: Authentication for retrieving the token
      description: Authenticate in order to get the token for further requests
      requestBody:
        content:
          "application/json":
            schema:
              $ref:  "#/components/schemas/authBody"
      responses:
        "200":
          description: Successfull response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authResponse'
  /authenticate/register:
    post:
      tags:
        - authenticate
      summary: Create a new subscription
      description: Create a new subscription in order to get a token for further requests
      requestBody:
        content:
          "application/json":
            schema:
              $ref:  "#/components/schemas/authRegister"
      responses:
        "200":
          description: Successfull response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authResponse'
  /channel/{channelId}:
    post:
      tags:
        - channel
      summary: Create a new chanel
      description: Creates a new channel for sending broadcasts within the namespace
      parameters:
        - name: channelId
          in: path
          description: ID of pet to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          "application/json":
            schema:
              $ref:  "#/components/schemas/authBody"
      responses:
        "200":
          description: Successfull response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authResponse'
components:
  schemas:
    authBody:
      type: object
      properties:
        email:
          type: "string"
          description: "A unique id like the mail address"
        password:
          type: "string"
          description: "The password of the depending clientId"
    authRegister:
      type: object
      properties:
        username:
          type: "string"
          description: "A unique identifier for the profile"
        email:
          type: "string"
          description: "A unique id like the mail address"
        password:
          type: "string"
          description: "The password of the depending clientId"
    authResponse:
      type: object
      properties:
        success:
          type: "boolean"
          description: "Indicates whether the request was successfull or not"
        token:
          type: "string"
          description: "The jwt token in order to verify further requests with the Rest API or Socket communication"